FROM node:20-alpine

ARG VITE_PORT
ENV VITE_PORT=$VITE_PORT

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE $VITE_PORT
CMD ["npm", "run", "dev"]
