server {
    listen 80;
    server_name campus-cart.ca;
    client_max_body_size 50M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name campus-cart.ca;
    client_max_body_size 50M;

    ssl_certificate     /etc/letsencrypt/live/campus-cart.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/campus-cart.ca/privkey.pem;

    location /api/ {
        proxy_pass http://backend:3001;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_cookie_path /api/ /;
        proxy_cache_bypass $http_upgrade;

        # add_header Access-Control-Allow-Origin campus-cart.ca;
        add_header Access-Control-Allow-Headers 'Content-Type, Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Max-Age' 86400;
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            return 204;
        }
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
