services:
  db:
    build:
      context: ./db
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_PORT: ${VITE_PORT}
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webroot:/var/www/certbot # ACME challenge path
      - certs:/etc/letsencrypt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - webroot:/var/www/certbot # ACME challenge path
      - certs:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly \
      --webroot -w /var/www/certbot \
      -d campus-cart.ca --agree-tos --non-interactive --register-unsafely-without-email"
    depends_on:
      - client

volumes:
  db-data:
  certs:
  webroot:

networks:
  app-network:
    driver: bridge
