services:
  backend:
    image: ghcr.io/manushpatell/campuscart/backend:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  client:
    image: ghcr.io/manushpatell/campuscart/client:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
