services:
  backend:
    image: ghcr.io/manushpatell/campuscart/backend:latest
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  client:
    image: ghcr.io/manushpatell/campuscart/client:latest
    container_name: client
    ports:
      - "443:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
